
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kampiewxracbdigxiwqy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImthbXBpZXd4cmFjYmRpZ3hpd3F5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2MTkwNzgsImV4cCI6MjA2MjE5NTA3OH0.CuAwS0JXcrb3ggt4lVLFZgh3la4LPaWD6bM4KzkrSmc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
